query ListMenus @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  menus {
    id
    name
    description
    restaurantId
  }
}

query GetMenuById($id: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  menu(key: { id: $id }) {
    id
    name
    description
    restaurantId
    categories {
      id
      name
      menuId
      items {
        id
        name
        description
        price
        categoryId
      }
    }
  }
}

mutation CreateMenu($name: String!, $description: String, $restaurantId: String!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  menu_insert(data: { name: $name, description: $description, restaurantId: $restaurantId })
}

mutation UpdateMenu($id: String!, $name: String, $description: String) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  menu_update(key: { id: $id }, data: { name: $name, description: $description })
}